version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accountancy
    ports:
      - "5432:5432"
  
  db-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./api
    ports:
      - "5000:8080"  # HTTP
      - "5001:443" # HTTPS
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=accountancy;Username=user;Password=password"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      # - ./api:/App

  # frontend:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend